  # GitHub MCP Tools (Alternative Python version)
  mcpo-github-python:
    image: ghcr.io/open-webui/mcpo:main
    container_name: local-mcpo-github-python
    ports:
      - "8102:8000"
    command: [
      "--host", "0.0.0.0", 
      "--port", "8000", 
      "--api-key", "${MCP_API_KEY}", 
      "--", 
      "uvx", "mcp-server-github"
    ]
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - local-ai-net
