version: '3.9'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    environment:
      - ENABLE_COMMUNITY_SHARING=false
      - ENABLE_MESSAGE_RATING=true
    volumes:
      - ./data/openwebui:/app/backend/data

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    ports:
      - "4000:4000"
    environment:
      - GEMINI_API_KEY=YOUR_GEMINI_API_KEY_HERE
    command: |
      --model gemini/gemini-pro
      --model gemini/gemini-pro-vision
      --model gemini/gemini-1.5-pro
      --model gemini/gemini-1.5-flash
      --port 4000