version: '3.9'

services:
  # Local PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: openwebui
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local-ai-net

  # Local Redis
  redis:
    image: redis:7-alpine
    container_name: local-redis
    networks:
      - local-ai-net

  # OpenWebUI
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: local-open-webui
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:localpassword@postgres:5432/openwebui
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - REDIS_URL=redis://redis:6379/0
      - ENABLE_COMMUNITY_SHARING=false
      - ENABLE_MESSAGE_RATING=true
      - DEFAULT_LOCALE=en
      - WEBUI_AUTH=false  # Disable auth for local testing
    volumes:
      - ./data/openwebui:/app/backend/data
    depends_on:
      - postgres
      - redis
    networks:
      - local-ai-net

  # Custom MCP server with OpenWebUI tools - temporarily disabled
  # Note: This requires fixing the stdio connection between MCPO and the Python-based MCP server
  # For now, use the working MCP tools (GitHub, Filesystem, Memory, Brave Search)
  
  # mcp-server:
  #   build: ./mcp-server
  #   container_name: local-mcp-server
  #   environment:
  #     - OPENWEBUI_URL=http://open-webui:8080
  #     - OPENWEBUI_API_KEY=${OPENWEBUI_API_KEY}
  #     - REDIS_URL=redis://redis:6379
  #   volumes:
  #     - ./data/workspace:/workspace
  #   networks:
  #     - local-ai-net
  #   ports:
  #     - "8888:8888"
  
  # mcpo-openwebui:
  #   image: ghcr.io/open-webui/mcpo:main
  #   container_name: local-mcpo-openwebui
  #   ports:
  #     - "8101:8000"
  #   # Needs proper stdio connection configuration
  #   networks:
  #     - local-ai-net

  # GitHub MCP Tools
  mcpo-github:
    image: ghcr.io/open-webui/mcpo:main
    container_name: local-mcpo-github
    ports:
      - "8102:8000"
    command: [
      "--host", "0.0.0.0", 
      "--port", "8000", 
      "--api-key", "${MCP_API_KEY}", 
      "--", 
      "npx", "-y", "@modelcontextprotocol/server-github"
    ]
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_TOKEN}
    networks:
      - local-ai-net

  # Filesystem MCP Tools
  mcpo-filesystem:
    image: ghcr.io/open-webui/mcpo:main
    container_name: local-mcpo-filesystem
    ports:
      - "8103:8000"
    command: [
      "--host", "0.0.0.0", 
      "--port", "8000", 
      "--api-key", "${MCP_API_KEY}", 
      "--", 
      "npx", "-y", "@modelcontextprotocol/server-filesystem", 
      "/workspace"
    ]
    volumes:
      - ./data/workspace:/workspace
    networks:
      - local-ai-net

  # Brave Search MCP Tools
  mcpo-brave-search:
    image: ghcr.io/open-webui/mcpo:main
    container_name: local-mcpo-brave-search
    ports:
      - "8104:8000"
    command: [
      "--host", "0.0.0.0", 
      "--port", "8000", 
      "--api-key", "${MCP_API_KEY}", 
      "--", 
      "npx", "-y", "@modelcontextprotocol/server-brave-search"
    ]
    environment:
      - BRAVE_API_KEY=${BRAVE_API_KEY}
    networks:
      - local-ai-net

  # Memory MCP Tools
  mcpo-memory:
    image: ghcr.io/open-webui/mcpo:main
    container_name: local-mcpo-memory
    ports:
      - "8105:8000"
    command: [
      "--host", "0.0.0.0", 
      "--port", "8000", 
      "--api-key", "${MCP_API_KEY}", 
      "--", 
      "npx", "-y", "@modelcontextprotocol/server-memory"
    ]
    volumes:
      - ./data/memory:/data/memory
    networks:
      - local-ai-net

  # LiteLLM for Gemini (Optional - remove if not using Gemini)
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: local-litellm
    ports:
      - "4000:4000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: [
      "--model", "gemini/gemini-1.5-flash",
      "--port", "4000"
    ]
    networks:
      - local-ai-net

networks:
  local-ai-net:
    driver: bridge

volumes:
  postgres-data:
